### ISSUE TITLE
Updates to Create button

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/SeaGrants#100]
The UX on the Create button is a little unintuitive. Let's:

- change the copy to "Create a pool"
- Remove the drop down — just have clicking on the button go straight to the create pool screen
![image](https://github.com/allo-protocol/SeaGrants/assets/15041635/ac907713-44b7-4745-bd05-dfb013da5532)
- add some spacing between the create button and the wallet drop-down
![image](https://github.com/allo-protocol/SeaGrants/assets/15041635/d7f7444b-b51d-4191-b514-133fbb7f9037)

**Comment by thelostone-mc** [comment]
- The dropdown cannot be removed as it can display new applications when you're on a specific pool page. 
We might have to figure out something more 
- Padding issue fixed via 62382b6

**Comment by thelostone-mc** [comment]
remove it
