### ISSUE TITLE
Ended pools in "show active"

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/SeaGrants#101]
When you click on the "show all active pools" drawer you're shown pools that are ended. This should only show pools that are active

![image](https://github.com/allo-protocol/SeaGrants/assets/15041635/267bab7f-b8ed-4d33-b015-7217265339fd)

**Comment by thelostone-mc** [comment]
Unable to reproduce this on local. This might be an issue on production

**Comment by 0xKurt** [comment]
possible problem:
nextjs pre-compiles the landing page and maybe the overview of the projects too.

So we're seeing the projects which were active on the day we compiled the page the last time.
And that's we can;t reproduce it locally - we simply re-compile the whole app including the landing page.
