### ISSUE TITLE
Start date error incorrect

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/SeaGrants#102]
The Start Date field throws an error if you try to create a pool sooner than 10 minutes in the future. However, it throws that same error even when the start date is further than 10 minutes

![image](https://github.com/allo-protocol/SeaGrants/assets/15041635/3125e7d6-0b31-4fcc-9e3f-bc48924b8c40)

**Comment by thelostone-mc** [comment]
Unable to reproduce this. I think even jason faced this. Could be with how we are dealing with localtimestamp
