### ISSUE TITLE
Application Form Discussion

### ISSUE THREAD

**Issue by 0xKurt** [allo-protocol/SeaGrants#20]
We need to know how an application form should look like and where the form data itself lives.

```json

{
  projectName,
  recipientAddress,
  description, // markdown
  ...
}

```

Regarding storing the form data we have two options:
- we hardcode the form in frontend
- we store the form data in the pool metdata and load it dynamically.
  - we could maybe utilize something like `useForms` (which feels a bit like an overkill) or https://www.npmjs.com/package/reactjs-form-builder to easily build the dynamic form

While the first one is the quicker approach, the second one is more modular and easily extendable in future.

Before we decide for the quick and dirty approach to reach our goal quicker, we should consider that grant programs may have different needs.

**Comment by thelostone-mc** [comment]
Would recommend keeping this in pool metadata
